# A simple chat plugin with channels.
# Copyright (C) 2013 Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

name: SimpleChat
main: me.hoot215.simplechat.SimpleChat
version: 1.0
author: Hoot215
softdepend: [Vault]
permissions:
  simplechat.*:
    description: 'Gives access to everything in SimpleChat'
    default: op
    children:
      simplechat.standard: true
      simplechat.colours: true
      simplechat.channel.list.hidden: true
      simplechat.unignorable: true
      simplechat.reload: true
      simplechat.refresh: true
      simplechat.mute: true
  simplechat.standard:
    description: 'Gives access to standard features in SimpleChat'
    default: true
    children:
      simplechat.simplechat: true
      simplechat.channel: true
      simplechat.ignore: true
      simplechat.talk: true
  simplechat.simplechat:
    description: "Gives access to the command '/simplechat'"
  simplechat.colours:
    description: 'Allows the use of colours in chat'
  simplechat.channel:
    description: "Gives access to the command '/channel'"
    children:
      simplechat.channel.list: true
  simplechat.channel.list:
    description: "Gives access to the command '/channel list'"
  simplechat.channel.list.hidden:
    description: "Show hidden channels when using '/channel list'"
  simplechat.ignore:
    description: "Gives access to the commands '/ignore' and '/unignore'"
  simplechat.unignorable:
    description: 'Prevents players with this permission being ignored'
  simplechat.mute:
    description: "Gives access to the commands '/mute' and '/unmute'"
  simplechat.talk:
    description: 'Allows the player to talk'
  simplechat.reload:
    description: "Gives access to the command '/simplechat reload'"
  simplechat.recache:
    description: "Gives access to the command '/simplechat recache'"
commands:
  simplechat:
    description: 'Displays SimpleChat info'
    permission: simplechat.simplechat
    permission-message: "§cYou don't have permission to use this command"
    usage: |
      §2==== §6§lSimpleChat §6by §lHoot215 §2====
      §a======== SimpleChat Help ========
      §9/<command> help §8- §fDisplays SimpleChat help
      §9/<command> reload §8- §fReloads config
      §9/<command> recache §8- §fRefreshes cache
    aliases: [chat, schat, sc]
  channel:
    description: 'Displays channel help'
    permission: simplechat.channel
    permission-message: "§cYou don't have permission to use this command"
    usage: |
      §2==== §6§lSimpleChat §6by §lHoot215 §2====
      §a======== §bChannel Help §a========
      §9/<command> help §8- §fDisplays channel help
      §9/<command> <name> §8- §fSet active channel to channel <name>
      §9/<command> join <name> §8- §fJoin channel <name>
      §9/<command> leave <name> §8- §fLeave channel <name>
      §9/<command> <name> <message> §8- §fSend <message> to channel <name>
      §9/<command> list §8- §fLists all channels (highlighting the ones you are in)
    aliases: [channels, ch]
  ignore:
    description: 'Ignores chat messages from a player'
    permission: simplechat.ignore
    permission-message: "§cYou don't have permission to use this command"
    usage: |
      §2==== §6§lSimpleChat §6by §lHoot215 §2====
      §a========= §cIgnore Help §a=========
      §9/<command> <players> §8- §fIgnores <players>
      §9/unignore <players> §8- §fUnignores <players>
  unignore:
    description: 'Stops ignoring chat messages from a player'
    permission: simplechat.ignore
    permission-message: "§cYou don't have permission to use this command"
    usage: |
      §2==== §6§lSimpleChat §6by §lHoot215 §2====
      §a========= §cIgnore Help §a=========
      §9/ignore <players> §8- §fIgnores <players>
      §9/<command> <players> §8- §fUnignores <players>
  mute:
    description: 'Prevents a player from talking'
    permission: simplechat.mute
    permission-message: "§cYou don't have permission to use this command"
    usage: |
      §2==== §6§lSimpleChat §6by §lHoot215 §2====
      §a========== §cMute Help §a==========
      §9/<command> <players> §8- §fMutes <players>
      §9/unmute <players> §8- §fUnmutes <players>
  unmute:
    description: 'Allows a player to talk again'
    permission: simplechat.mute
    permission-message: "§cYou don't have permission to use this command"
    usage: |
      §2==== §6§lSimpleChat §6by §lHoot215 §2====
      §a========== §cMute Help §a==========
      §9/mute <players> §8- §fMutes <players>
      §9/<command> <players> §8- §fUnmutes <players>
